services:
  postgresdb:
    image: postgres:15-alpine
    container_name: internet-cinema-db
    restart: unless-stopped
    env_file: ./trade-app/.env
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    ports:
      - "${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    build: ./trade-app
    container_name: internet-cinema-app
    restart: unless-stopped
    env_file: ./trade-app/.env
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    environment:
      - DB_HOST=postgresdb
      - DB_USER=${POSTGRESDB_USER}
      - DB_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - DB_NAME=${POSTGRESDB_DATABASE}
      - DB_PORT=${POSTGRESDB_DOCKER_PORT}
    stdin_open: true
    tty: true

volumes:
  db:

