services:
  postgresdb:
    image: postgres:15-alpine
    container_name: internet-cinema-db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}  # <-- обязательно POSTGRES_PASSWORD
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    ports:
      - "${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: ./trade-app
    container_name: internet-cinema-app
    depends_on:
      - postgresdb
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "6868:8080"   # локальный порт 6868 → порт контейнера 8080
    environment:
      - DB_HOST=postgresdb
      - DB_USER=${POSTGRESDB_USER}
      - DB_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - DB_NAME=${POSTGRESDB_DATABASE}
      - DB_PORT=5432
    stdin_open: true
    tty: true

volumes:
  db:

